package za.ac.nwu.domain.persistence;

//import lombok.*;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Objects;

/*@Getter
@Setter
@EqualsAndHashCode
@ToString
@AllArgsConstructor
@NoArgsConstructor
@NonNull*/
@Entity
@Table(name = "Member", schema = "Member_Schema")
public class Member implements Serializable {

    private static final long serialVersionUID = -6965549404196897257L;
    private Integer MemID;

    private String Mem_FirstName;

    private String Mem_LastName;

    private String Mem_Email;

    private String Mem_Phone_Number;

    public Member() {
    }

    public Member(String mem_FirstName, String mem_LastName, String mem_Email, String mem_Phone_Number) {
        Mem_FirstName = mem_FirstName;
        Mem_LastName = mem_LastName;
        Mem_Email = mem_Email;
    }

    public Member(Integer memID, String mem_FirstName, String mem_LastName, String mem_Email, String mem_Phone_Number) {
        MemID = memID;
        Mem_FirstName = mem_FirstName;
        Mem_LastName = mem_LastName;
        Mem_Email = mem_Email;
        Mem_Phone_Number = mem_Phone_Number;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //id column automatically generated by db
    public Integer getMemID() {
        return MemID;
    }

    public void setMemID(Integer memID) {
        MemID = memID;
    }

    public String getMem_FirstName() {
        return Mem_FirstName;
    }

    public void setMem_FirstName(String mem_FirstName) {
        Mem_FirstName = mem_FirstName;
    }

    public String getMem_LastName() {
        return Mem_LastName;
    }

    public void setMem_LastName(String mem_LastName) {
        Mem_LastName = mem_LastName;
    }

    public String getMem_Email() {
        return Mem_Email;
    }

    public void setMem_Email(String mem_Email) {
        Mem_Email = mem_Email;
    }

    public String getMem_Phone_Number() {
        return Mem_Phone_Number;
    }

    public void setMem_Phone_Number(String mem_Phone_Number) {
        Mem_Phone_Number = mem_Phone_Number;
    }

    @Override
    public String toString() {
        return "Member{" +
                "MemID=" + MemID +
                ", Mem_FirstName='" + Mem_FirstName + '\'' +
                ", Mem_LastName='" + Mem_LastName + '\'' +
                ", Mem_Email='" + Mem_Email + '\'' +
                ", Mem_Phone_Number='" + Mem_Phone_Number + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Member member = (Member) o;
        return Objects.equals(MemID, member.MemID) && Objects.equals(Mem_FirstName, member.Mem_FirstName) && Objects.equals(Mem_LastName, member.Mem_LastName) && Objects.equals(Mem_Email, member.Mem_Email) && Objects.equals(Mem_Phone_Number, member.Mem_Phone_Number);
    }

    @Override
    public int hashCode() {
        return Objects.hash(MemID, Mem_FirstName, Mem_LastName, Mem_Email, Mem_Phone_Number);
    }
}
